name: Auto PR for Feature Branches

on:
  push:
    branches:
      - 'feature/*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref_name }}
          title: "Merge ${{ github.ref_name }} into main"
          body: "This pull request was automatically created from ${{ github.ref_name }}."
          draft: false
