name: Run test

on: [push]

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23'
      
      - run: go version

      - name: Run go test
        run: go test ./...

